### ISSUE TITLE
test.h5 share

### ISSUE THREAD

**Issue by Kakoedlinnoeslovo** [RyotaImai/-Keras-Image2StyleGAN-#2]
Hi, @RyotaImai, thank you for work, can you please share test.h5 file, because the links from https://github.com/NVlabs/stylegan didn't work and I can't convert the model using your method. Thank you in advance!

**Comment by RyotaImai** [comment]
Sorry for late response.
Ok! I updated this repository's README. Please download from the kink on the README.
